spring:
  application:
    name: Assignment Management System
  
  datasource:
    url: jdbc:mysql://localhost:3306/assignment_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: "#San2020"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  
  main:
    banner-mode: console
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /

file:
  upload-dir: ./uploads

jwt:
  secret: mySecretKey
  expirationMs: 86400000

cors:
  allowed-origins: http://localhost:5173

info:
  app:
    name: Assignment Management System
    description: A comprehensive assignment management system for teachers and students
    version: 1.0.0

logging:
  level:
    root: INFO
    com.assignmentmanagement: INFO
    org.springframework.boot: INFO
    org.springframework.web: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"